### ISSUE TITLE
Source code is unavailable unless you have admin rights

### ISSUE THREAD

**Issue by vantiegh** [jenkinsci/cobertura-plugin#102]
When using version 1.12.1 of the plug-in the source code can only be seen when you have admin rights on jenkins. If that's not the case, you get

Source code is unavailable. Some possible reasons are:
-  This is not the most recent build (to save on disk space, this plugin only keeps the most recent build’s source code). 
- Cobertura found the source code but did not provide enough information to locate the source code. 
- Cobertura could not find the source code, so this plugin has no hope of finding it. 
- You do not have sufficient permissions to view this file. - 

Is there a solution for that ?

**Comment by ewortzman** [comment]
I'd like to see this addressed as well. There's no reason source code should be hidden from non-admins.

**Comment by KevinOlsthoorn** [comment]
I thought I was facing the same issue but realized that I wasn't logged in at all. I think that makes sense. I assume you are logged in as a user?

**Comment by aiudirog** [comment]
This appears to be still unresolved and is quite frustrating. I was just running a Jenkins tutorial session and discovered my users couldn't see their source code while I could.
