### ISSUE TITLE
Source code is unavailable (Cobertura plugin 1.10)

### ISSUE THREAD

**Issue by vitalykarasik** [jenkinsci/cobertura-plugin#103]
I'm producing coverage report by coverage.py and use "Publish cobertura report".
I do have "Cobertura Coverage Report" , but couldn't not see Python sources.
Can please someone point to to the document or example or proper coverage.xml file?
I reviewed coverage.xml, and filenames seem be right - "/opt/mydir/mypackage/vitaly.py".
In the same time into "Coverage Breakdown by File" section of report  I see this path without leading slash, i.e. "opt/mydir/mypackage/vitaly.py". 

Seems to be different from #102 - I do have admin right.

TIA,
Vitaly

**Comment by henryborchers** [comment]
I'm having the same issue

**Comment by henryborchers** [comment]
@jeffpearce  I'm actually trying out the new Jenkins Coverage Adapter for Cobertura so mine might be a little different.  The xml file parses correctly but the generated report doesn't link to the source files 
https://github.com/UIUCLibrary/Speedwagon/blob/87f25a04097350ff9f7283b8e0d3949b272e6af5/Jenkinsfile 
line 317

**Comment by milos-u** [comment]
Same issue for me
![obrazek](https://user-images.githubusercontent.com/3037291/52204610-f5670e80-2874-11e9-90fa-2e9088bad6d3.png)

**Comment by cizezsy** [comment]
@milos-u You need to click the name of sub-element to enter next level to see source files. You can see them below the chart you trying to click.
