### ISSUE TITLE
Support for Ocean Blue report

### ISSUE THREAD

**Issue by anton-johansson** [jenkinsci/cobertura-plugin#106]
I'd love to see the code coverage report in Ocean Blue. Any plans on this?

**Comment by adrach** [comment]
any update?

**Comment by medianick** [comment]
Likely not going to happen -- take a look at https://issues.jenkins-ci.org/browse/JENKINS-55359

**Comment by jeffpearce** [comment]
I missed that discussion. @anton-johansson - any objections to me closing this issue, since Blue Ocean seems to be abandoned?

**Comment by anton-johansson** [comment]
No objections!
