### ISSUE TITLE
Cobertura Plugin for Declarative pipeline

### ISSUE THREAD

**Issue by ghost** [jenkinsci/cobertura-plugin#107]
New to declarative pipelines and i have been searching far and wide regarding cobertura code coverage. I did find and tried to implement

  ```
post {
    always {
    cobertura coberturaReportFile: '*.xml'
           }
    }
```

but i am getting this error:

 ` java.lang.NoSuchMethodError: No such DSL method 'cobertura' found among steps`

can some one direct me on how to implement this within a declarative pipeline, as there is not much docmentation on this. I would assume its something similar to :

```
stage('Test') {
			steps {
				cobertura#command#here
			}	
}		
```

**Comment by jeffpearce** [comment]
Do you have the declarative pipeline plugins installed?

Sent from my iPhone

On Oct 25, 2018, at 1:13 PM, equate76 <notifications@github.com<mailto:notifications@github.com>> wrote:


New to declarative pipelines and i have been searching far and wide regarding cobertura code coverage. I did find and tried to implement

post {
  always {
  cobertura coberturaReportFile: '*.xml'
         }
  }


but i am getting this error:

java.lang.NoSuchMethodError: No such DSL method 'cobertura' found among steps

can some one direct me on how to implement this within a declarative pipeline, as there is not much docmentation on this. I would assume its something similar to :

stage('Test') {
                        steps {
                                cobertura#command#here
                        }
}

**Comment by equate76** [comment]
I do, pipe line is working successfully, only problem is trying to install cobertura and I get the message above

**Comment by martinmosegaard** [comment]
The `cobertura` DSL method is provided by this plugin. I know it sounds silly, but have you installed that?

**Comment by shay-berman** [comment]
I have the same issue.

 post {
        always {
            junit 'build/reports/*.xml'
            cobertura coberturaReportFile: 'build/reports/*.xml'
        }
but it fail with the same issue. Any idea how to fix it?


"java.lang.NoSuchMethodError: No such DSL method 'cobertura' found among steps [ArtifactoryGradleBuild, MavenDescriptorStep, addBadge, addErrorBadge, addHtmlBadge, addInfoBadge, addInteractivePromotion, addShortText, addWarningBadge, ansiblePlaybook, ansibleVault, archive, artifactoryDistributeBuild, artifactoryDownload, artifactoryMavenBuild, artifactoryPromoteBuild, artifactoryUpload, bat, build, catchError, checkout, collectEnv, conanAddRemote, conanAddUser, createSummary, deleteDir, deployArtifacts, dir, dockerFingerprintFrom, dockerFingerprintRun, dockerPullStep, dockerPushStep, dockerPushWithProxyStep, echo, emailext, emailextrecipients, envVarsForTool, error, fileExists, getArtifactoryServer, getContext, git, initConanClient, input, isUnix, jiraComment, jiraIssueSelector, jiraSearch, junit, library, libraryResource, load, lock, logstash, mail, milestone, newArtifactoryServer, newBuildInfo, newGradleBuild, newMavenBuild, node, parallel, powershell, properties, publishBuildInfo, publishHTML, pwd, readFile, readTrusted, removeBadges, removeHtmlBadges, removeSummaries, resolveScm, retry, runConanCommand, script, sh, slackSend, sleep, stage, stash, step, svn, task, timeout, timestamps, tm, tool, unarchive, unstash, vSphere, validateDeclarativePipeline, waitUntil, withContext, withCredentials, withDockerContainer, withDockerRegistry, withDockerServer, withEnv, withMaven, wrap, writeFile, ws, xrayScanBuild] or symbols [all, allOf, always, ant, antFromApache, antOutcome, antTarget, any, anyOf, apiToken, architecture, archiveArtifacts, artifactManager, artifactsPublisher, batchFile, bitbucket, booleanParam, branch, brokenBuildSuspects, brokenTestsSuspects, buildButton, buildDiscarder, buildParameter, buildingTag, caseInsensitive, caseSensitive, certificate, changeRequest, changelog, changeset, checkoutToSubdirectory, choice, choiceParam, cleanWs, clock, cloud, command, concordionPublisher, configFile, configFileProvider, copyArtifactPermission, copyArtifacts, credentials, cron, crumb, culprits, defaultView, demand, dependenciesFingerprintPublisher, developers, disableConcurrentBuilds, disableResume, docker, dockerCert, dockerfile, downloadSettings, downstream, dumb, durabilityHint, envVars, environment, equals, expression, file, fileParam, filePath, findbugsPublisher, fingerprint, frameOptions, freeStyle, freeStyleJob, fromScm, fromSource, git, gitBranchDiscovery, gitParameter, gitTagDiscovery, github, githubPush, globalConfigFiles, gradle, headRegexFilter, headWildcardFilter, hyperlink, hyperlinkToModels, installSource, invokerPublisher, isRestartedRun, jacocoPublisher, jdk, jdkInstaller, jgit, jgitapache, jgivenPublisher, jnlp, jobName, junitPublisher, label, lastCompleted, lastDuration, lastFailure, lastGrantedAuthorities, lastStable, lastSuccess, lastSuccessful, latestSavedBuild, legacy, legacySCM, list, local, location, logRotator, loggedInUsersCanDoAnything, logstashSend, masterBuild, maven, maven3Mojos, mavenErrors, mavenLinkerPublisher, mavenMojos, mavenWarnings, modernSCM, myView, newContainerPerStage, node, nodeProperties, nonStoredPasswordParam, none, not, nunit, openTasksPublisher, overrideIndexTriggers, paneStatus, parameters, password, pattern, permalink, permanent, pipeline-model, pipelineGraphPublisher, pipelineMaven, pipelineTriggers, plainText, plugin, pollSCM, preserveStashes, projectNamingStrategy, proxy, queueItemAuthenticator, quietPeriod, recipients, remotingCLI, requestor, run, runParam, schedule, scmRetryCount, scriptApprovalLink, search, security, shell, skipDefaultCheckout, skipStagesAfterUnstable, slackNotifier, slave, snapshotDependencies, sourceRegexFilter, sourceWildcardFilter, specific, spotbugsPublisher, sshPublisher, sshPublisherDesc, sshTransfer, sshUserPrivateKey, stackTrace, standard, status, string, stringParam, swapSpace, tag, text, textParam, tmpSpace, toolLocation, unsecured, upstream, upstreamDevelopers, userSeed, usernameColonPassword, usernamePassword, viewsTabBar, weather, withAnt, workspace, zfs, zip] or globals [Artifactory, buildScbTestJob, configureStorage, configureVMware, createScbVm, currentBuild, deleteScbVm, deployScb, docker, env, manager, params, pipeline, scm, slackReportBack2Stable, slackReportFailure, xaviCheckOutScm, xaviRevertVmsToSnapshot]
"

**Comment by pradyumna1979** [comment]
check if you have code coverage api plugin is there or not

**Comment by UltimateGeek** [comment]
@jeffpearce , this issue can be closed as user error with not having the plugin installed.

**Comment by jeffpearce** [comment]
@UltimateGeek - thanks for bringing it to my attentions!
