### ISSUE TITLE
Code Coverage API not showing file breakdown

### ISSUE THREAD

**Issue by dpogue** [jenkinsci/cobertura-plugin#108]
I'm publishing cobertura coverage information using the new Jenkins Code Coverage API:

```groovy
publishCoverage adapters: [coberturaAdapter('coverage/coverage.xml')], sourceFileResolver: sourceFiles('STORE_LAST_BUILD')
```

I see the coverage widget and link to the report for the job, but within that report it's not broken down by file, class, package, etc.

**Comment by cizezsy** [comment]
@dpogue You may need to click the name of the child summary chart item to enter the next level. The default name is 'project'. 

And, If you cannot find the item, could you provide a screenshot? Thanks!

**Comment by dpogue** [comment]
Ahh, okay... I guess I was expecting that first "project" level to already be expanded
