### ISSUE TITLE
Explain how to use coverage targets

### ISSUE THREAD

**Issue by martinmosegaard** [jenkinsci/cobertura-plugin#111]
Is it possible to add documentation to the `cobertura` pipeline step parameters here: https://jenkins.io/doc/pipeline/steps/cobertura/ ?

I had to dig into https://github.com/jenkinsci/cobertura-plugin/blob/cbe06a5974494fb3775730edf7506b47bdd8d109/src/main/java/hudson/plugins/cobertura/CoberturaPublisher.java#L760 to discover how to set the `lineCoverageTargets` value for example.

Then I figured out that the value is a string of `"healthy %, unhealthy %, unstable %"` (but what does that mean with respect to build results?)

An experiment where the actual line coverage is 77% would give the following results:

- Setting `lineCoverageTargets: '100, 90, 80'` caused the build to fail with the message: `Failing build due to unstability`
- Setting `lineCoverageTargets: '100, 90, 0'` caused the build to fail with the message: `Failing build because it is unhealthy.`
- Setting `lineCoverageTargets: '100, 0, 0'` caused the build to pass with a message about new health minimum and new stability minimum

**Comment by benwilkes9** [comment]
Any update on this?

**Comment by sajanep** [comment]
It is too bad so that these parameters are not documented in a decent way.

**Comment by cizezsy** [comment]
After looking at the codes, I think the first parameter is useless, the second is used for healthy threshold, the third is used for stable threshold.

If the `failUnhealthy` is set to true, this plugin will fail the build if coverage is lower than the second parameter.

If coverage is lower than the third parameter, it will mark the build as unstable. And if the `failUnstable ` is set to true, it will fail the build instead.

**Comment by amanda-skilljar** [comment]
https://github.com/jenkinsci/cobertura-plugin/pull/68

With ` lineCoverageTargets: '90.0, 80.1, 50'`:
>- Report health as 100% if line coverage > 90%
>- Report health as 0% if line coverage < 80.1%
>- Mark build as unstable if line coverage < 50%

**Comment by aedades** [comment]
https://github.com/jenkinsci/cobertura-plugin/pull/68

With `lineCoverageTargets: '90.0, 80.1, 50'`:

>- Report health as 100% if line coverage > 90%
>- Report health as 0% if line coverage < 80.1%
>- Mark build as unstable if line coverage < 50%

**Comment by ocofaigh** [comment]
Don't suppose anybody managed to get a descrition toigether for all of the paramters listed here: https://jenkins.io/doc/pipeline/steps/cobertura/ ?

**Comment by pieron187** [comment]
You can find a bit of explanation on Jenkins terminology page. 

https://wiki.jenkins.io/display/JENKINS/Terminology

**Stable build** - A build is stable if it was built successfully and no publisher reports it as unstable.

**Unstable build** - A build is unstable if it was built successfully and one or more publishers report it unstable. For example, if the JUnit publisher is configured and a test fails then the build will be marked unstable.

**Successful build**  - A build is successful when the compilation reported no errors.

**Broken build / Failed build** - A build is broken if it failed during building. That is, it is not successful.

**Comment by jlurena** [comment]
THANK YOU
