### ISSUE TITLE
Marking job as unstable should be visualised at a stage level

### ISSUE THREAD

**Issue by grabowski-d** [jenkinsci/cobertura-plugin#118]
Currently, if a Cobertura check fails, the whole job becomes unstable and all stages (in the Blue Ocean view) are marked with yellow colour. With multiple stages, it is difficult to find the reason for instability. There is a new API that could be used to do so:
https://jenkins.io/blog/2019/07/05/jenkins-pipeline-stage-result-visualization-improvements/

It is possible to implement such a solution?

**Comment by cizezsy** [comment]
According to the post, we need to upgrade our baseline Jenkins version to 2.138.4(now it is 2.60.3). What do you think about this changes? @jeffpearce
