### ISSUE TITLE
Cannot reset ratcheted targets

### ISSUE THREAD

**Issue by arogge** [jenkinsci/cobertura-plugin#124]
I have an (intentional) regression in test coverage which makes my builds fail.
Now I would need to reset the ratcheted target values, but cannot find a way to do it.

**Comment by davidritter** [comment]
We are having the same issue. Not sure how to upvote this, so just posting me too!

**Comment by jpvandervelden** [comment]
I also ran into this issue when removing obsolete code. @davidritter's workaround work, but indeed is not elegant. I would like to have a proper solution to reset these values.
