### ISSUE TITLE
Compare metric to last master build

### ISSUE THREAD

**Issue by TobiasSchaffner** [jenkinsci/cobertura-plugin#126]
The cobertura plugin has some shortcomings when it comes to working with feature branches.

**Behaviour**

* When working with Health/Stability auto update, the first build of a new feature branch falls back to the default values.
* Further test results are compared to the last successful build.

**Leads to**

* Feature branches are marked as successful with a lower coverage than the master branch if the first build of the feature branch has a lower coverage.
* False failing builds of the feature branch if there was a build that had a higher coverage in the process of implementing the feature.

**Expected behaviour**

* Allow to only autoupdate Health/Stability for a specific branch (e.g. master or develop)
* Allow to reference the last build before branching for all other branches.

![image](https://user-images.githubusercontent.com/10929490/104476667-c9a44580-55c0-11eb-81d6-b31389366992.png)

Looking forward to your feedback!

**Comment by RayOei** [comment]
The unstable builds on rebuilds with changes in coverage calculations which are minute is annoying to say the least.
Example 78.40% -> 78.36% will mark as unstable while the minimum was set at 70%. It is solvable by removing previous builds but that is cumbersome. Looking at the age of this issue I fear it won't be addresses any time soon ...
