### ISSUE TITLE
No coverage report generated when project directory is set

### ISSUE THREAD

**Issue by MoriTanosuke** [jenkinsci/cobertura-plugin#3]
I'm trying to get a coverage report with the cobertura plugin, but the graph and data shows no entries. When I browse my workspace to the coverage.xml I can see content in this file. When I run my scripts to generate the coverage.xml manually, the report is filled too.

In my project setup I specify a different directory as workspace. I suspect that this is the cause of my problem. I tried to find a place in the sourcecode where this happens, but I'm not yet sure.

**Comment by mbarrien** [comment]
Closing old ticket.
