### ISSUE TITLE
Java 7 support

### ISSUE THREAD

**Issue by soulless9** [jenkinsci/cobertura-plugin#30]
I was looking through the history of the updates and it explicitly says when the plugin was updated to work with JDK 5 and 6. I was wondering if the current plugin works with JDK 7. I know people are using it but it seems to have a good many problems. So does it actually work with Java 7, or are people just finding work-arounds for the problems they run into? Also what are the dependent versions of Jenkins, Maven, and Cobertura  needed for the current plugin? (1.9.5)

**Comment by christ66** [comment]
The cobertura plugin works with java 7. Cobertura however requires 2.0+ for it to properly parse java 7 binaries.
