### ISSUE TITLE
Help running locally

### ISSUE THREAD

**Issue by technimadhu** [jenkinsci/cobertura-plugin#31]
Team, great job on the plugin . Works great on jenkins.

Question. Would you guys consider developing a standalone viewer (without jenkins). I have the test framework (jasmine/jscover) which generates this cobertura xml file. I would like to view this in report format locally (without using jenkins) to see how much code is covered, before i submit my tests etc.. Dont need all the bells and whistles , just something which shows graphically in html/css which lines are covered and which is not.

If you guys have no time, can someone point me which classes i can look at to try and implement something like this.

Thanks.

**Comment by christ66** [comment]
This is more of a cobertura question, than a Jenkins cobertura plugin. If you would like to replace the default cobertura html formatter with a custom one you can replace the content in: https://github.com/cobertura/cobertura/blob/master/cobertura/src/main/java/net/sourceforge/cobertura/reporting/html/HTMLReport.java.
