### ISSUE TITLE
Links in dashboard are wrong

### ISSUE THREAD

**Issue by agaengel** [jenkinsci/cobertura-plugin#32]
Sine the update of jenkins to 1.572 on a dashboard with Code Coverages(Cobertura) portlet the links to the job contain twice the part /view/viewname.

So all links end up in a 404

**Comment by KostyaSha** [comment]
please try l.9.7 that should appear in update center tomorrow

**Comment by jeffpearce** [comment]
@agaengel - were you able to resolve this? I think this issue can be closed
