### ISSUE TITLE
Specify the directory of the source code.

### ISSUE THREAD

**Issue by drgarcia1986** [jenkinsci/cobertura-plugin#38]
If my source is not at root of workspace, plugin does not find the files.
Like this [issue](https://issues.jenkins-ci.org/browse/JENKINS-13889).

**Comment by GabLeRoux** [comment]
2 years later, did you manage to fix this?
I seem to get the exact same problem today.

**Comment by jeffpearce** [comment]
@drgarcia1986 - can we close this issue now?
