### ISSUE TITLE
Make compatible with Jenkins Workflow/Pipeline plugin for report publishing

### ISSUE THREAD

**Issue by 60secs** [jenkinsci/cobertura-plugin#50]
The Jenkins Workflow/Pipeline plugin does not support post build steps. To support it, plugins need to make changes as outline in the Plugin Developer Guide at:

https://github.com/jenkinsci/workflow-plugin/blob/master/COMPATIBILITY.md

See corresponding issue in Jenkins Issue tracker
https://issues.jenkins-ci.org/browse/JENKINS-30700

**Comment by leth** [comment]
I'm working a changeset for this, but I could do with some advice from someone more familiar with how Jenkins plugins work, as I'm mostly guessing and copying from the junit and xunit plugins.
I'll post a PR with more info in the next couple of days.

**Comment by leth** [comment]
These are the areas I could use some advice on: https://github.com/leth/cobertura-plugin/commit/52a2ce9b2ec9dde01ff9054e1184c2e833e00a60

**Comment by stijnvn** [comment]
@leth, any chance to get your changes merged in the near feature?

**Comment by leth** [comment]
Sorry, I've not got around to working on it recently; I would need to find the time to do some more digging to understand the refactoring needed.

So no, it's not likely to be soon, sorry. Feel free to work on it if you find time to do so before I do!

On 14 March 2016 13:29:06 GMT+00:00, Stijn Van Nieuwenhuyse <notifications@github.com> wrote:
>@leth, any chance to get your changes merged in the near feature?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jenkinsci/cobertura-plugin/issues/50#issuecomment-196310064

-- 
Sent from my phone. Please excuse my brevity.

**Comment by vekexasia** [comment]
Keep us updated @leth

**Comment by s0undt3ch** [comment]
I've been waiting for this support for a while now, unfortunately I do not know enough Java to do it myself or I would.

Are there any plans to implement this? Besides eventually of course.

**Comment by rudicba** [comment]
+1

**Comment by karlhaas** [comment]
+1

**Comment by kapi** [comment]
+1

**Comment by ceelian** [comment]
+1

**Comment by nickbroon** [comment]
I think what's needed is to implement the `SimpleBuildStep` interface. similar to what the xunit plugin does: https://github.com/jenkinsci/xunit-plugin/blob/master/src/main/java/org/jenkinsci/plugins/xunit/XUnitPublisher.java#L63

**Comment by nickbroon** [comment]
I brought this issue up here https://groups.google.com/forum/#!msg/jenkinsci-users/UnAK_1YASa0/0TPbYN7HBQAJ

**Comment by snajo** [comment]
+1

**Comment by DJViking** [comment]
+1

**Comment by IvanAnishchuk** [comment]
Any news?

**Comment by francisdb** [comment]
Can we have a release (and docs) for this?

**Comment by nickbroon** [comment]
I don't think it's been fully implemented yet.

**Comment by francisdb** [comment]
@mbarrien mind to let us know what the state of this ticket is?

**Comment by cernenwein** [comment]
+1

**Comment by arpheno** [comment]
+1

**Comment by RockLobster** [comment]
+1

**Comment by Hochoban** [comment]
+1

**Comment by rpocase** [comment]
+1

**Comment by nickbroon** [comment]
Pull Request #55 appears to be to add this feature request.

**Comment by zackpollard** [comment]
Any update on this? Seems like a great shame that this isn't getting implemented. Seems like #55 is mostly there, but has some issues right now. Anyone who is a contributor on this project able to give an update regarding whether this will be implemented soon?

**Comment by sxamit** [comment]
+1

**Comment by GabLeRoux** [comment]
This is a feature killer, is there a way we can help here? I see there's currently 6 commits referencing this. Anyone with experience with Jenkins pipeline and cobertura-plugin could provide us with details on what's left to do and or what could be done to finish this faster?

I'm not very familiar with Java nor jenkins plugin development, but I really want this feature. If I can do something to help here, I'd be very happy to contribute.

**Comment by Mashi** [comment]
+1

**Comment by trisb** [comment]
+1

**Comment by alexb5** [comment]
+1

**Comment by Saucistophe** [comment]
+1

**Comment by svalchinov** [comment]
+1 for 2017!!!!

**Comment by clems4ever** [comment]
+1

**Comment by gruetter** [comment]
+1

**Comment by jdrosensweig** [comment]
+1

**Comment by marytanfin** [comment]
+1

**Comment by mikkiweesenaar** [comment]
+1

**Comment by ahmed1490** [comment]
+1

**Comment by eamonnfaherty** [comment]
+1

**Comment by optimistAk** [comment]
+1

**Comment by jeffjk-me** [comment]
+1

**Comment by eczeek** [comment]
+1

**Comment by aadis** [comment]
+1

**Comment by ThomasOSI** [comment]
+1

**Comment by a-a-ronCC** [comment]
+1

**Comment by alshabib** [comment]
+1

**Comment by kugel-** [comment]
+1

**Comment by Kleinitay** [comment]
+1

**Comment by bruno-lopes** [comment]
Any news on this issue?

**Comment by alexmojaki** [comment]
+1

**Comment by nonmanifold** [comment]
+1

**Comment by gelblars** [comment]
+1

**Comment by y0n1** [comment]
👍

**Comment by HereWeAreFromFrance** [comment]
+1

**Comment by DanielKoehler** [comment]
+1

**Comment by morganchristiansson** [comment]
+1

**Comment by sielay** [comment]
+1 +10 +100 +1000 +10000

**Comment by mamghari** [comment]
Any news on it ?

**Comment by GabLeRoux** [comment]
See progress in #55 Someone just requested a merge on master.

**Comment by gabrielcsapo** [comment]
+1

**Comment by kulkarnisu** [comment]
+1

**Comment by zephiyr** [comment]
+1

**Comment by vrommer** [comment]
+1

**Comment by nergal** [comment]
+1

**Comment by Tautvis** [comment]
+1

**Comment by ADobrodey** [comment]
+1

**Comment by KenLai** [comment]
+1

**Comment by mbarrien** [comment]
Fixed in version 1.10 which has been uploaded to the repo. Waiting until it shows up in update center before closing this issue.

**Comment by SuperBarracuda** [comment]
I can see that the plugin has now been published. Does anyone know the pipeline syntax for using it?

Other jenkins plugins support the pipeline syntax generator but I can't see cobertura listed under sample steps.

**Comment by lsglick** [comment]
@SuperBarracuda: If you select the `step: General Build Step` sample step, you'll see an option to `Publish Cobertura Coverage Report`.

I haven't used it yet, but seems like it is all there.

![image](https://cloud.githubusercontent.com/assets/5394693/25432882/48cc30f8-2a54-11e7-9efb-47e30cd6751b.png)

**Comment by reinout** [comment]
I have a line like this:

       step([$class: 'CoberturaPublisher', coberturaReportFile: 'coverage.xml'])

(My coverage output is in `coverage.xml`). Works like a charm again.

**Comment by SuperBarracuda** [comment]
@reinout @lsglick Thanks I have it working now. However the snippet doesn't seem to generate "	Coverage Metric Targets" for lines. Do you know how this would be specified?

**Comment by rpocase** [comment]
@lsglick I'm not seeing Step: General Build Step in my snippet generator. Is there possibly another plugin I'm missing? Using the snippet that @reinout mentioned works, though.

**Comment by nuzz** [comment]
The default output from the snippet generator I get is:step([$class: 'CoberturaPublisher',
                        autoUpdateHealth: false,
                        autoUpdateStability: false,
                        coberturaReportFile: 'coverage.xml',
                        failUnhealthy: false,
                        failUnstable: false,
                        maxNumberOfBuilds: 0,
                        onlyStable: false,
                        sourceEncoding: 'ASCII',
                        zoomCoverageChart: false])

**Comment by gena01** [comment]
Would it make sense to add @ Symbol("cobertura") or a different one so it's easier to use/find?

**Comment by akhy** [comment]
the "coverage metrics target" cannot be generated, need this to fail the build if the coverage is below certain threshold

**Comment by mbarrien** [comment]
Released last week. Please file new issues for any bug found in the pipeline code.

**Comment by LizaKelly** [comment]
@lsglick is this the pipeline groovy plugin you are using?

**Comment by anton-johansson** [comment]
I also cannot get the `Coverage metrics target` generated by the snippet generator. Anyone knows how to code my pipeline to include it?

**Comment by esmaras** [comment]
+1 for `Coverage metrics target` from pipeline step
