### ISSUE TITLE
Results not published when jenkins job fails

### ISSUE THREAD

**Issue by clarkli86** [jenkinsci/cobertura-plugin#59]
The **Consider only stable builds** option says - *_Include only stable builds, i.e. exclude unstable and failed ones. *_

But when the job actually fails, Cobertura prints "Skipping Cobertura coverage report as build was not UNSTABLE or better ..." and quits.

**Comment by jdamme** [comment]
I have the same problem. A failed unit test sets the build to fail. 
I unchecked  "Consider only stable builds" option to be able to still get the updated cover report but it also prints "Skipping Cobertura coverage report as build was not UNSTABLE or better ..."

**Comment by eugene-cloudinary** [comment]
+1

**Comment by clarkli86** [comment]
@jenkinsci Could this issue please be looked into?

**Comment by bataliero** [comment]
same here

**Comment by jeffpearce** [comment]
@clarkli86  Which version of the plugin are you using? This is supposed to be fixed in the latest release

**Comment by jeffpearce** [comment]
I'm going to go ahead and close this issue. Please open a new one if you are still seeing issues with the most recent release of the plugin

**Comment by dejewi** [comment]
I see very similar error:
ERROR: Step ‘Publish Cobertura Coverage Report’ failed: [Cobertura] Failing build due to unstability.

(Cobertura plugin v1.12, Jenkins v2.92)

**Comment by morganchristiansson** [comment]
This is issue is also reported in Jenkins bug tracker https://issues.jenkins-ci.org/browse/JENKINS-23642
