### ISSUE TITLE
Example of PublisherTarget on pipeline

### ISSUE THREAD

**Issue by JorisAndrade** [jenkinsci/cobertura-plugin#67]
Hi,

I used the new release of the plugin with this step

step([$class: 'CoberturaPublisher', coberturaReportFile: 'coverage.xml', onlyStable: false])

How can I set healthy/unhealthy/unstable target using pipeline syntax ?

Thanks in advance,

**Comment by rifkyalikiki** [comment]
+1
```
step([$class: 'CoberturaPublisher',
          autoUpdateHealth: false,
          autoUpdateStability: false,
          coberturaReportFile: '**/coverage.xml',
          failUnhealthy: false,
          failUnstable: false,
          maxNumberOfBuilds: 0,
          onlyStable: false,
          sourceEncoding: 'ASCII',
          zoomCoverageChart: false])
```
But I need to configure coveragemetrics

**Comment by jeffpearce** [comment]
II don't think it as exposed in the pipeline. I'll work on a PR to fix that

**Comment by rifkyalikiki** [comment]
Nice! Thanks @jeffpearce 🙇

**Comment by jeffpearce** [comment]
Closing this issue since this is in the released plugin now
