### ISSUE TITLE
Is autoUpdateHealth, autoUpdateStability supported with Jenkins pipeline?

### ISSUE THREAD

**Issue by j03m** [jenkinsci/cobertura-plugin#72]
I noticed that the syntax generator for the plugin that when I check off autoUpdateStability and autoUpdateHealth the options are left out of my final syntax.

When false:

```
step([$class: 'CoberturaPublisher', autoUpdateHealth: false, autoUpdateStability: false, coberturaReportFile: 'coverage.xml', maxNumberOfBuilds: 0, onlyStable: false, sourceEncoding: 'ASCII', zoomCoverageChart: false])
```

When true: 
```
step([$class: 'CoberturaPublisher', autoUpdateHealth: false, autoUpdateStability: false, coberturaReportFile: 'coverage.xml', maxNumberOfBuilds: 0, onlyStable: false, sourceEncoding: 'ASCII', zoomCoverageChart: false])
```
Which made me question if this was supported in pipeline? I've had some trouble validating regressions.

**Comment by j03m** [comment]
Also as an aside is it possible to set the Coverage Metric Targets from the jenkins file?

**Comment by stefangoor** [comment]
There seems to be an open PR for the targets here: https://github.com/jenkinsci/cobertura-plugin/pull/68

I am also looking for the autoUpdateHealth, autoUpdateStability functionality

**Comment by stefangoor** [comment]
The autoUpdateHealth and autoUpdateStability don't appear to work for me either

**Comment by jeffpearce** [comment]
@j03m - I don't see any reason in the code these would be handled differently between pipeline and non-pipeline. Can you give me a specific scenario that's different to help me understand the problem?

**Comment by stefangoor** [comment]
Hi Jeff,

I'll test again with the new release but the way I was expecting to work was that when I run tests that pass the coverage target is set to that level and if it dips below that threshold on the next build it fails.

For example, we set a threshold of 80% and a build runs and passes with 85% coverage so the new target is 85%.  A subsequent build has 83% so it fails because it doesn't meet the autoupdated target.

This is how we used to use the plugin before we switched to pipelines.  I see there was a new release so I'll test the new version and see how it goes.  I think the fact the targets weren't working properly previously for pipelines was linked to this.

Thanks for all the effort you have put into this, I really like the plugin and appreciate all the work you put in.

Thanks,
Stefan

**Comment by stefangoor** [comment]
This is working for me now, I had not set the initial targets by accident but now it is applying the targets correctly and automatically updating the threshold.

Thanks so much for adding this in the latest release, it's a real help to us!

**Comment by blalapeta** [comment]
Hi All,

Any one tell me, if the Cobertura-plugin is supporting for Pipeline jobs in Jenkins?

If yes, pl. share the sample Pipeline code and POM.xml and configurations steps at Jenkins side? as we are going to implement the same for our project.

Thanks for your support.

Regards,
Balu

**Comment by jeffpearce** [comment]
You can see the full syntax from the  `Pipeline Syntax` link:

![screenshot 2018-05-07 09 10 08](https://user-images.githubusercontent.com/1479145/39712085-9b41a228-51d6-11e8-944b-b0c6dc18a9e7.png)

Most options are optional, all you really need is  `cobertura coberturaReportFile: '*.xml'`

**Comment by sirsavary** [comment]
Attempting to get ratcheting working with no luck. Jenkinsfile l post-build step looks like:

```
post {
        always {
            junit "**/xunit.xml"
            cobertura coberturaReportFile: "**/cobertura-coverage.xml"
            cleanWs()
        }
    }
```

Output from build #1:
```
[Cobertura] Publishing Cobertura coverage report...
[Cobertura] Publishing Cobertura coverage results...
[Cobertura] Cobertura coverage report found.
    Methods's new health minimum is: 2.91
    Lines's new health minimum is: 12.62
    Conditionals's new health minimum is: 0.64
    Methods's new stability minimum is: 2.91
    Lines's new stability minimum is: 12.62
    Conditionals's new stability minimum is: 0.64
```

Output from build #2:
```
[Cobertura] Publishing Cobertura coverage report...
[Cobertura] Publishing Cobertura coverage results...
[Cobertura] Cobertura coverage report found.
    Methods's new health minimum is: 2.91
    Lines's new health minimum is: 10.83
    Conditionals's new health minimum is: 0.67
    Methods's new stability minimum is: 2.91
    Lines's new stability minimum is: 10.83
    Conditionals's new stability minimum is: 0.67
```

I'm not sure if the values aren't persisting or if I'm misunderstanding how this feature is intended to work.
