### ISSUE TITLE
When coverage goes down threshold is updated and the build is not marked as unstable

### ISSUE THREAD

**Issue by lexotero** [jenkinsci/cobertura-plugin#89]
Using the snippet generator I've added the following step to my `Jenkinsfile`:

```
cobertura coberturaReportFile: 'coverage.xml', conditionalCoverageTargets: '80, 0, 0', failUnhealthy: true, failUnstable: true, lineCoverageTargets: '80, 0, 0', maxNumberOfBuilds: 0, methodCoverageTargets: '80, 0, 0', onlyStable: false, sourceEncoding: 'ASCII', zoomCoverageChart: false
```

This should set the initial threshold to 80% for lines, methods and conditionals and auto-update the minimum when the build is successful (as `autoUpdateHealth` and `autoUpdateStability` are `true` by default). But when coverage goes down the threshold is updated and the build is not marked as unstable:

The pipeline steps reports the update of the thresholds:
```
    Methods's new health minimum is: 78.84
    Lines's new health minimum is: 82.19
    Conditionals's new health minimum is: 72.23
    Methods's new stability minimum is: 78.84
    Lines's new stability minimum is: 82.19
    Conditionals's new stability minimum is: 72.23
```

In other non-pipeline jobs using the `cobertura-plugin`, when the coverage is bellow the minimum the coverage does not get updated and the build is marked as unstable.

**Environment**

- Jenkins v.2.73.3
- Cobertura plugin v1.12
- Pipeline plugin v2.5
- Pipeline: API plugin v2.23.1

**Comment by sackdan** [comment]
I confirm the behaviour.

Jenkins v2.73.2
Cobertura Plugin v1.12.1
Pipeline Plugin v2.5
Pipeline API Plugin v2.27

This pretty much breaks the Cobertura plugin for me...

**Comment by Greatlemer** [comment]
Does anyone have any ideas about what's wrong here, or workarounds to get this working again? My team has been struggling with this for a few months now since switching to pipelines.

**Comment by zihaoyu** [comment]
Does not seem to work for me either. Cobertura plugin v1.12.1

**Comment by mixels** [comment]
This is affecting us in version 1.13. Ditto on this essentially breaking the plugin for me and my team.

**Comment by lexotero** [comment]
To give more details. Using the following Jenkinsfile:

```groovy
node('my-node') {
    [...]
    
    stage('Publish coverage report') {
        archive "coverage.xml"
    
        cobertura(
            coberturaReportFile: "coverage.xml",
            onlyStable: false,
            failNoReports: true,
            failUnhealthy: false,
            failUnstable: false,
            autoUpdateHealth: true,
            autoUpdateStability: true,
            zoomCoverageChart: true,
            maxNumberOfBuilds: 0,
            lineCoverageTargets: '80, 80, 80',
            conditionalCoverageTargets: '80, 80, 80',
            classCoverageTargets: '80, 80, 80',
            fileCoverageTargets: '80, 80, 80',
        )
    }
}
```

If the `coverage.xml` gives a line coverage of 75%, the build would be marked as unstable (the same would happened for conditional, class and file coverage).
On the other hand if `coverage.xml` gives a higher (>80%) line coverage, the plugin will say that the target has been adjusted to that new percentage, but actually it isn't.

Every time you run the job, the **targets will be set to the value provided by the `Jenkinsfile`**. Therefore in this example, if the coverage is over 80%, the build will be marked as successful, if the coverage is under 80% the build will be marked as unstable. If you first get a 100% coverage and in the next build you get a 90%, the build will still be successful because the target won't be updated, it will always be 80% unless you keep updating the `Jenkinsfile` every time your coverage goes up.

**Comment by nysander** [comment]
Was **autoUpdateStability** fixed or is it broken atm?

**Comment by sauliusgrigaitis** [comment]
Looks like it's broken as we also have issues with passing builds with degraded coverage.

**Comment by sackdan** [comment]
Any news on this front?

**Comment by cizezsy** [comment]
This plugin actually update the threshold, but it will always be overrided by value configured in Jenkinsfile. Let me handle this and try to fix it.

**Comment by lexotero** [comment]
> This plugin actually update the threshold, but it will always be overrided by value configured in Jenkinsfile. Let me handle this and try to fix it.

Thank you for having a look on that!!

In my comment https://github.com/jenkinsci/cobertura-plugin/issues/89#issuecomment-453506691_ I tried to clarify the behavior I am experiencing. It's been a while since I don't revisit this, but it seems that we might have 2 different problems:

- (From my comment) The pipeline job will always use the thresholds set in the Jenkinsfile rather than the updated thresholds from previous builds.
- (From the bug description) The thresholds are reported as updated when the coverage goes down. It should mark the build as unstable and don't update the previous thresholds. You always want your coverage to go up.

**Comment by cizezsy** [comment]
@lexotero I think the third value in the `methodCoverageTargets` option is used for stable threshold, so it won't mark build as unstable as you config it to zero.

**Comment by lexotero** [comment]
> @lexotero I think the third value in the `methodCoverageTargets` option is used for stable threshold, so it won't mark build as unstable as you config it to zero.

You are right, I have checked the Jenkins Pipeline syntax, and indeed it says that the third value is to set the build as unstable if the coverage drops below that number.

That solves the problem with setting the state of the build. I can confirm that with the configuration in https://github.com/jenkinsci/cobertura-plugin/issues/89#issuecomment-453506691, the build is marked as unstable if the coverage drops below 80%.

The problem then is that we have too update the Jenkinsfile configuration to make sure we always use the latest/highest coverage results as the threshold.

I have seen your pull request. I hope it gets merged soon and we get the fix. Thank you very much!
